blank_issues_enabled: true
contact_links:
  - name: LinuxMusicians MusE Forum
    url: https://linuxmusicians.com/viewforum.php?f=61
    about: Use for help requests and general discussions about MusE.
